name: cli-dictionary
base: core18
version: latest
summary: cli-dictionary
description: |
  Get a word's meaning from a command line!
  Languages: English, Portuguese Brazil, Hindi
  Spanish, French, Japanese, Russian, German, Italian
  Korean, Chinese (simplified), Arabic, Turkish
grade: stable
confinement: strict

apps:
  cli-dictionary:
    command: bin/cli-dictionary
    plugs:
      - network
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
  
parts:
  cli-dictionary:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - requests
